name: Push to Lokalise
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
      GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
      VAR_LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
      VAR_LOKALISE_PROJECT_ID: ${{ vars.LOKALISE_PROJECT_ID }}
      VAR_LOKALISE_SOURCE_LANG_ISO: ${{ vars.LOKALISE_SOURCE_LANG }}
      VAR_LOKALISE_FOLDER_PATH: ${{ vars.LOKALISE_TRANSLATIONS_PATH }}
      VAR_GIT_DEFAULT_BRANCH: ${{ vars.VAR_GIT_DEFAULT_BRANCH }}

    steps:
      # Checkout the repository to the GitHub runner
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history of the repository to ensure all commits are available

      # Download and install the Lokalise CLI tool
      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      # Lokalise Branching
      - name: List Lokalise Branches
        id: lokalise_branches
        run: |
          LOKALISE_BRANCHES=$(./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
          --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}" \
          branch list | jq -r '.branches[].name')
          
          echo -e "Lokalise branches:\n$LOKALISE_BRANCHES"
          echo "$LOKALISE_BRANCHES" > lokalise_branches.txt
        
      # Debug step to read the contents of lokalise_branches.txt
      - name: Debug - Show Lokalise Branches
        run: |
          echo "Contents of lokalise_branches.txt:"
          cat lokalise_branches.txt

      # Compare Lokalise Branch names to Git Triggering Branch
      - name: Compare Lokalise Branch names to Git Triggering Branch
        run: |
          GIT_BRANCH_NAME="${{ github.ref_name }}"
          LOKALISE_BRANCHES=$(cat lokalise_branches.txt)  # Read the contents of the file into the LOKALISE_BRANCHES variable
            
          if [ "$GIT_BRANCH_NAME" = "$VAR_GIT_DEFAULT_BRANCH" ]; then
            echo "Your default branch in Lokalise is Master and default GIT branch name is $VAR_GIT_DEFAULT_BRANCH. Master/main exists in Lokalise"
          elif echo "$LOKALISE_BRANCHES" | grep -qw "$GIT_BRANCH_NAME"; then
            echo "Branch $GIT_BRANCH_NAME exists in Lokalise."
          else
            echo "Branch $GIT_BRANCH_NAME does not exist in Lokalise."
            exit 1
          fi
