name: Push to Lokalise
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
      GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
      VAR_LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
      VAR_LOKALISE_PROJECT_ID: ${{ vars.LOKALISE_PROJECT_ID }}
      VAR_LOKALISE_SOURCE_LANG_ISO: ${{ vars.LOKALISE_SOURCE_LANG }}
      VAR_LOKALISE_FOLDER_PATH: ${{ vars.LOKALISE_TRANSLATIONS_PATH }}
      VAR_GIT_DEFAULT_BRANCH: ${{ vars.GIT_DEFAULT_BRANCH }}
      VAR_GIT_UPSTREAM_BRANCH: ${{ vars.GIT_UPSTREAM_BRANCH }}

    steps:
      # Checkout the repository to the GitHub runner
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history of the repository to ensure all commits are available


      # Download and install the Lokalise CLI tool
      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh


      # Check for changed and new files in Git
      - name: Get all changed files between branches
        run: |
          # Initialize the changed_files.txt file
          > changed_files.txt

          # Check if the branch is the default branch 
          if [ "${{ github.ref_name }}" = "${{ vars.GIT_DEFAULT_BRANCH }}" ]; then
            echo "Changed localization files between HEAD~1 and HEAD:"
            git diff --name-only HEAD~1 HEAD -- '${{ vars.LOKALISE_TRANSLATIONS_PATH }}/${{ vars.LOKALISE_SOURCE_LANG }}/**' | tee -a changed_files.txt
          else
          # Fetch the upstream branch
            git fetch origin ${{ vars.GIT_UPSTREAM_BRANCH }}:${{ github.ref_name }}-upstream
          # Fetch the current branch
            git fetch origin ${{ github.ref_name }}:${{ github.ref_name }}-current
            echo "Changed localization files between ${{ vars.GIT_UPSTREAM_BRANCH }} and ${{ github.ref_name }}:"
            git diff --name-only ${{ github.ref_name }}-upstream...${{ github.ref_name }}-current -- '${{ vars.LOKALISE_TRANSLATIONS_PATH }}/${{ vars.LOKALISE_SOURCE_LANG }}/**' | tee -a changed_files.txt
          fi
          
      # Debug read contents of changed_files.txt
      - name: Debug - changed_files.txt
        run: |
          echo "Contents of changed_files.txt:"
          cat changed_files.txt


      # Lokalise Branching
      - name: List Lokalise Branches
        id: lokalise_branches
        run: |
          LOKALISE_BRANCHES=$(./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
          --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}" \
          branch list | jq -r '.branches[].name')
          
          echo -e "Lokalise branches:\n$LOKALISE_BRANCHES"
          echo "$LOKALISE_BRANCHES" > lokalise_branches.txt
        

      # Compare Lokalise Branch names to Git Triggering Branch
      - name: Compare Lokalise Branch names to Git Triggering Branch
        run: |
          GIT_BRANCH_NAME="${{ github.ref_name }}"
          LOKALISE_BRANCHES=$(cat lokalise_branches.txt)  # Read the contents of the file into the LOKALISE_BRANCHES variable
            
          if [ "$GIT_BRANCH_NAME" = "${{ env.VAR_GIT_DEFAULT_BRANCH }}" ]; then
            echo "Your default branch in Lokalise is Master and default GIT branch name is $VAR_GIT_DEFAULT_BRANCH. Master/main exists in Lokalise. Continuing on Lokalise Master"
            echo LOKALISE_BRANCH="Master"
            echo "$LOKALISE_BRANCH" > lokalise_branch.txt
            echo "push_to_Lokalise_master"="true" >> $GITHUB_ENV

          elif echo "$LOKALISE_BRANCHES" | grep -qw "$GIT_BRANCH_NAME"; then
            echo "Branch $GIT_BRANCH_NAME exists in Lokalise. Continuing on Lokalise branch."
            echo LOKALISE_BRANCH="$GIT_BRANCH_NAME"
            echo "$LOKALISE_BRANCH" > lokalise_branch.txt
            echo "push_to_Lokalise_master"="false" >> $GITHUB_ENV
            
            
          else
            echo "Branch $GIT_BRANCH_NAME does not exist in Lokalise. Will create a branch in Lokalise."
            echo LOKALISE_BRANCH="$GIT_BRANCH_NAME"
            echo "$LOKALISE_BRANCH" > lokalise_branch.txt
            echo "branch_exists=false" >> $GITHUB_ENV
            echo "push_to_Lokalise_master"="false" >> $GITHUB_ENV
          fi

      # Debug LOKALISE_BRANCH
      - name: Debug
        run: |
          echo "Value of LOKALISE_BRANCH:"
          LOKALISE_BRANCH=$(cat lokalise_branch.txt)
          echo "$LOKALISE_BRANCH"

      # Debug env.VAR push_to_Lokalise_master
      - name: Debug
        run: |
          echo "Value of push_to_Lokalise_master: ${{ env.push_to_Lokalise_master }}"

      # Create a new branch in Lokalise if it doesn't exist
      - name: Create Lokalise Branch
        if: env.branch_exists == 'false'
        run: |
          # Fetch the branch name from lokalise_branch.txt
          LOKALISE_BRANCH=$(cat lokalise_branch.txt)

          # Create a new branch in Lokalise using the fetched branch name and capture the HTTP response
          ./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
          --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}" \
          branch create \
          --name "$LOKALISE_BRANCH"

          # Check if the API response contains a 200 status
          HTTP_STATUS=$(echo "$RESPONSE" | jq -r '.status_code')
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to create branch in Lokalise. HTTP Status: $HTTP_STATUS"
            exit 1
          else
            echo "Branch created successfully in Lokalise. HTTP Status: $HTTP_STATUS"
          fi

      # Push changed files to Lokalise Branch
      - name: Push files to Lokalise Branch
        if: env.push_to_Lokalise_master == 'false'
        run: | 
          # Fetch the branch name from lokalise_branch.txt
          LOKALISE_BRANCH=$(cat lokalise_branch.txt)
          echo "Fetched branch name: $LOKALISE_BRANCH"
          
          # Read changed files from changed_files.txt
          if [ -f changed_files.txt ]; then
            changed_files=$(cat changed_files.txt | grep -E '^pub/locales/en/.*\.json$')
          else
            echo "No changed_files.txt file found. Exiting."
            exit 1
          fi
            
          echo "Changed files to push to Lokalise:"
          echo "$changed_files"
        
          # Loop through each changed file and upload it to Lokalise
          for file in $changed_files; do
            if [ -f "$file" ]; then
              echo "Uploading $file to Lokalise..."
              ./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
              --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}:$LOKALISE_BRANCH" \
              file upload \
              --file="$file" \
              --lang-iso="${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}" \
              --replace-modified \
              --include-path \
              --distinguish-by-file \
              --poll \
              --poll-timeout=120s \
              --tag-inserted-keys \
              --tag-skipped-keys=true \
              --tag-updated-keys \
              --tags ${{ github.ref_name }}
            else
              echo "File $file does not exist."
            fi
          done


      # Push changed files to Lokalise Master
      - name: Push files to Lokalise Master
        if: env.push_to_Lokalise_master == 'true'
        run: |
          # Fetch the branch name from lokalise_branch.txt
          LOKALISE_BRANCH=$(cat lokalise_branch.txt)
          echo "Fetched branch name: $LOKALISE_BRANCH"
          
          # Read changed files from changed_files.txt
          if [ -f changed_files.txt ]; then
            changed_files=$(cat changed_files.txt | grep -E '^pub/locales/en/.*\.json$')
          else
            echo "No changed_files.txt file found. Exiting."
            exit 1
          fi
            
          echo "Changed files to push to Lokalise:"
          echo "$changed_files"
        
          # Loop through each changed file and upload it to Lokalise
          for file in $changed_files; do
            if [ -f "$file" ]; then
              echo "Uploading $file to Lokalise..."
              ./bin/lokalise2 --token="${{ env.VAR_LOKALISE_API_TOKEN }}" \
              --project-id="${{ env.VAR_LOKALISE_PROJECT_ID }}:$LOKALISE_BRANCH" \
              file upload \
              --file="$file" \
              --lang-iso="${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}" \
              --replace-modified \
              --include-path \
              --distinguish-by-file \
              --poll \
              --poll-timeout=120s \
              --tag-inserted-keys \
              --tag-skipped-keys=true \
              --tag-updated-keys \
              --tags ${{ github.ref_name }}
            else
              echo "File $file does not exist."
            fi
          done